import "@/assets/stylesheets/globals.sass";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import ReduxProvider from "@/utils/redux/ReduxProvider";

import ContainerLayout from "@/lib/container/ContainerLayout";
import Navbar from "@/lib/components/Navbar";

const opensans = Open_Sans({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "faruuhan — Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${opensans.className}`}>
        <ReduxProvider>
          <Navbar />
          <ContainerLayout>{children}</ContainerLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
