import "@/assets/stylesheets/globals.sass";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import Sidebar from "@/components/Sidebar";

const opensans = Open_Sans({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={opensans.className + `flex `}>
        <div className='mx-auto lg:w-[1024px] flex min-h-screen lg:gap-5 my-10'>
          <div className='w-3/12'>
            <Sidebar />
          </div>
          <div className='w-9/12'>{children}</div>
        </div>
      </body>
    </html>
  );
}
